In [1]:
pip install bs4

Requirement already satisfied: bs4 in c:\users\madhu\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\madhu\anaconda3\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\madhu\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install requests

Requirement already satisfied: requests in c:\users\madhu\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\madhu\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\madhu\anaconda3\lib\site-packages (from requests) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\madhu\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\madhu\anaconda3\lib\site-packages (from requests) (2021.10.8)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [17]:
Movies = []

try:
    source = requests.get('https://www.imdb.com/chart/top/')
    source.raise_for_status()
    
    soup = BeautifulSoup(source.text,'html.parser')
    
    movies = soup.find('tbody', class_="lister-list").find_all('tr')
    
    for movie in movies:
        rank = movie.find('td', class_="titleColumn").get_text(strip=True)[0]
        name = movie.find('td', class_="titleColumn").a.text
        year = movie.find('td', class_="titleColumn").span.text
        rating = movie.find('td', class_="ratingColumn").strong.text
        
        print(rank, name, year, rating)
        Movies.append([rank, name, year, rating])
        
except Error as er:
    print(er)

1 The Shawshank Redemption (1994) 9.2
2 The Godfather (1972) 9.2
3 The Dark Knight (2008) 9.0
4 The Godfather Part II (1974) 9.0
5 12 Angry Men (1957) 9.0
6 Schindler's List (1993) 8.9
7 The Lord of the Rings: The Return of the King (2003) 8.9
8 Pulp Fiction (1994) 8.8
9 The Lord of the Rings: The Fellowship of the Ring (2001) 8.8
1 Il buono, il brutto, il cattivo (1966) 8.8
1 Forrest Gump (1994) 8.8
1 Fight Club (1999) 8.7
1 The Lord of the Rings: The Two Towers (2002) 8.7
1 Inception (2010) 8.7
1 The Empire Strikes Back (1980) 8.7
1 The Matrix (1999) 8.7
1 GoodFellas (1990) 8.7
1 One Flew Over the Cuckoo's Nest (1975) 8.6
1 Se7en (1995) 8.6
2 It's a Wonderful Life (1946) 8.6
2 Shichinin no samurai (1954) 8.6
2 The Silence of the Lambs (1991) 8.6
2 Saving Private Ryan (1998) 8.6
2 Cidade de Deus (2002) 8.6
2 Interstellar (2014) 8.6
2 La vita è bella (1997) 8.6
2 The Green Mile (1999) 8.6
2 Star Wars (1977) 8.5
2 Terminator 2: Judgment Day (1991) 8.5
3 Back to the Future (1985) 8.5
3 Sen to Chihiro no kamikakushi (2001) 8.5
3 The Pianist (2002) 8.5
3 Psycho (1960) 8.5
3 Gisaengchung (2019) 8.5
3 Léon (1994) 8.5
3 The Lion King (1994) 8.5
3 Gladiator (2000) 8.5
3 American History X (1998) 8.5
3 The Departed (2006) 8.5
4 Whiplash (2014) 8.5
4 The Prestige (2006) 8.5
4 The Usual Suspects (1995) 8.5
4 Casablanca (1942) 8.5
4 Hotaru no haka (1988) 8.5
4 Seppuku (1962) 8.5
4 The Intouchables (2011) 8.5
4 Modern Times (1936) 8.4
4 Once Upon a Time in the West (1968) 8.4
4 Nuovo Cinema Paradiso (1988) 8.4
5 Rear Window (1954) 8.4
5 Alien (1979) 8.4
5 City Lights (1931) 8.4
5 Apocalypse Now (1979) 8.4
5 Memento (2000) 8.4
5 Django Unchained (2012) 8.4
5 Raiders of the Lost Ark (1981) 8.4
5 WALL·E (2008) 8.4
5 The Lives of Others (2006) 8.4
5 Sunset Blvd. (1950) 8.4
6 Paths of Glory (1957) 8.4
6 The Shining (1980) 8.4
6 The Great Dictator (1940) 8.4
6 Avengers: Infinity War (2018) 8.4
6 Witness for the Prosecution (1957) 8.4
6 Aliens (1986) 8.3
6 Spider-Man: Into the Spider-Verse (2018) 8.3
6 American Beauty (1999) 8.3
6 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) 8.3
6 The Dark Knight Rises (2012) 8.3
7 Oldeuboi (2003) 8.3
7 Inglourious Basterds (2009) 8.3
7 Amadeus (1984) 8.3
7 Coco (2017) 8.3
7 Toy Story (1995) 8.3
7 Braveheart (1995) 8.3
7 Joker (2019) 8.3
7 Das Boot (1981) 8.3
7 Avengers: Endgame (2019) 8.3
7 Mononoke-hime (1997) 8.3
8 Once Upon a Time in America (1984) 8.3
8 Good Will Hunting (1997) 8.3
8 Kimi no na wa. (2016) 8.3
8 Singin' in the Rain (1952) 8.3
8 3 Idiots (2009) 8.3
8 Requiem for a Dream (2000) 8.3
8 Tengoku to jigoku (1963) 8.3
8 Toy Story 3 (2010) 8.3
8 Capharnaüm (2018) 8.3
8 Star Wars: Episode VI - Return of the Jedi (1983) 8.3
9 2001: A Space Odyssey (1968) 8.3
9 Eternal Sunshine of the Spotless Mind (2004) 8.3
9 Idi i smotri (1985) 8.3
9 Reservoir Dogs (1992) 8.3
9 Jagten (2012) 8.3
9 Citizen Kane (1941) 8.2
9 Lawrence of Arabia (1962) 8.2
9 M - Eine Stadt sucht einen Mörder (1931) 8.2
9 Ikiru (1952) 8.2
9 North by Northwest (1959) 8.2
1 Vertigo (1958) 8.2
1 The Apartment (1960) 8.2
1 Le fabuleux destin d'Amélie Poulain (2001) 8.2
1 Double Indemnity (1944) 8.2
1 A Clockwork Orange (1971) 8.2
1 Full Metal Jacket (1987) 8.2
1 Scarface (1983) 8.2
1 Hamilton (2020) 8.2
1 Incendies (2010) 8.2
1 Heat (1995) 8.2
1 To Kill a Mockingbird (1962) 8.2
1 Up (2009) 8.2
1 The Sting (1973) 8.2
1 Jodaeiye Nader az Simin (2011) 8.2
1 Metropolis (1927) 8.2
1 L.A. Confidential (1997) 8.2
1 Taxi Driver (1976) 8.2
1 Die Hard (1988) 8.2
1 Indiana Jones and the Last Crusade (1989) 8.2
1 Snatch (2000) 8.2
1 Ladri di biciclette (1948) 8.2
1 Taare Zameen Par (2007) 8.2
1 1917 (2019) 8.2
1 Top Gun: Maverick (2022) 8.2
1 Der Untergang (2004) 8.2
1 Dangal (2016) 8.2
1 Per qualche dollaro in più (1965) 8.2
1 Batman Begins (2005) 8.2
1 The Kid (1921) 8.2
1 Some Like It Hot (1959) 8.2
1 The Father (2020) 8.2
1 All About Eve (1950) 8.2
1 The Wolf of Wall Street (2013) 8.2
1 Green Book (2018) 8.2
1 Judgment at Nuremberg (1961) 8.2
1 Ran (1985) 8.2
1 Casino (1995) 8.2
1 The Truman Show (1998) 8.2
1 There Will Be Blood (2007) 8.2
1 Pan's Labyrinth (2006) 8.2
1 Unforgiven (1992) 8.2
1 The Sixth Sense (1999) 8.2
1 Shutter Island (2010) 8.2
1 A Beautiful Mind (2001) 8.2
1 Jurassic Park (1993) 8.2
1 Yôjinbô (1961) 8.1
1 The Treasure of the Sierra Madre (1948) 8.1
1 Monty Python and the Holy Grail (1975) 8.1
1 No Country for Old Men (2007) 8.1
1 Kill Bill: Vol. 1 (2003) 8.1
1 The Great Escape (1963) 8.1
1 Rashômon (1950) 8.1
1 The Thing (1982) 8.1
1 Spider-Man: No Way Home (2021) 8.1
1 Finding Nemo (2003) 8.1
1 The Elephant Man (1980) 8.1
1 Chinatown (1974) 8.1
1 Raging Bull (1980) 8.1
1 V for Vendetta (2005) 8.1
1 Gone with the Wind (1939) 8.1
1 Lock, Stock and Two Smoking Barrels (1998) 8.1
1 Dial M for Murder (1954) 8.1
1 Inside Out (2015) 8.1
1 Hauru no ugoku shiro (2004) 8.1
1 El secreto de sus ojos (2009) 8.1
1 Three Billboards Outside Ebbing, Missouri (2017) 8.1
1 Trainspotting (1996) 8.1
1 The Bridge on the River Kwai (1957) 8.1
1 Prisoners (2013) 8.1
1 Fargo (1996) 8.1
1 Warrior (2011) 8.1
1 Gran Torino (2008) 8.1
1 Catch Me If You Can (2002) 8.1
1 Tonari no Totoro (1988) 8.1
1 Million Dollar Baby (2004) 8.1
1 John Wick: Chapter 4 (2023) 8.1
1 Bacheha-Ye aseman (1997) 8.1
1 Blade Runner (1982) 8.1
1 The Gold Rush (1925) 8.1
1 Klaus (2019) 8.1
1 Harry Potter and the Deathly Hallows: Part 2 (2011) 8.1
1 Before Sunrise (1995) 8.1
1 12 Years a Slave (2013) 8.1
1 Ben-Hur (1959) 8.1
1 On the Waterfront (1954) 8.1
1 The Grand Budapest Hotel (2014) 8.1
1 Gone Girl (2014) 8.1
1 Smultronstället (1957) 8.1
1 The General (1926) 8.1
1 Barry Lyndon (1975) 8.1
1 In the Name of the Father (1993) 8.1
1 The Deer Hunter (1978) 8.1
1 The Third Man (1949) 8.1
1 Hacksaw Ridge (2016) 8.1
1 Le salaire de la peur (1953) 8.1
1 Salinui chueok (2003) 8.1
1 Relatos salvajes (2014) 8.1
1 Sherlock Jr. (1924) 8.1
1 Mr. Smith Goes to Washington (1939) 8.1
1 Mad Max: Fury Road (2015) 8.1
2 Mary and Max. (2009) 8.1
2 Det sjunde inseglet (1957) 8.1
2 How to Train Your Dragon (2010) 8.1
2 Monsters, Inc. (2001) 8.1
2 Dead Poets Society (1989) 8.1
2 Jaws (1975) 8.1
2 Room (2015) 8.1
2 The Big Lebowski (1998) 8.1
2 Tôkyô monogatari (1953) 8.1
2 La passion de Jeanne d'Arc (1928) 8.1
2 Ford v Ferrari (2019) 8.1
2 Hotel Rwanda (2004) 8.0
2 Rocky (1976) 8.0
2 Platoon (1986) 8.0
2 Ratatouille (2007) 8.0
2 Spotlight (2015) 8.0
2 Logan (2017) 8.0
2 The Terminator (1984) 8.0
2 Stand by Me (1986) 8.0
2 Rush (2013) 8.0
2 Network (1976) 8.0
2 Before Sunset (2004) 8.0
2 Into the Wild (2007) 8.0
2 The Wizard of Oz (1939) 8.0
2 The Best Years of Our Lives (1946) 8.0
2 The Exorcist (1973) 8.0
2 Groundhog Day (1993) 8.0
2 The Incredibles (2004) 8.0
2 To Be or Not to Be (1942) 8.0
2 La haine (1995) 8.0
2 Pirates of the Caribbean: The Curse of the Black Pearl (2003) 8.0
2 Pather Panchali (1955) 8.0
2 La battaglia di Algeri (1966) 8.0
2 Hachi: A Dog's Tale (2009) 8.0
2 The Grapes of Wrath (1940) 8.0
2 Jai Bhim (2021) 8.0
2 Babam ve Oglum (2005) 8.0
2 Amores perros (2000) 8.0
2 Rebecca (1940) 8.0
2 Ah-ga-ssi (2016) 8.0
2 Cool Hand Luke (1967) 8.0
2 The Sound of Music (1965) 8.0
2 Les quatre cents coups (1959) 8.0
2 It Happened One Night (1934) 8.0
2 Persona (1966) 8.0
2 Life of Brian (1979) 8.0
2 The Iron Giant (1999) 8.0
2 The Help (2011) 8.0
2 Aladdin (1992) 8.0
2 Dersu Uzala (1975) 8.0
2 Dances with Wolves (1990) 8.0

In [18]:
df = pd.DataFrame(Movies,columns= ['rank', 'name', 'year', 'rating'])

In [19]:
df.head(250)

    rank                      name    year rating
0      1  The Shawshank Redemption  (1994)    9.2
1      2             The Godfather  (1972)    9.2
2      3           The Dark Knight  (2008)    9.0
3      4     The Godfather Part II  (1974)    9.0
4      5              12 Angry Men  (1957)    9.0
..   ...                       ...     ...    ...
245    2            The Iron Giant  (1999)    8.0
246    2                  The Help  (2011)    8.0
247    2                   Aladdin  (1992)    8.0
248    2               Dersu Uzala  (1975)    8.0
249    2        Dances with Wolves  (1990)    8.0

[250 rows x 4 columns]

In [7]:
df.to_csv("IMDB Top Rated Movies")